### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by murphypetercl** [powersync-ja/vue-supabase-todolist-template#4]
Hi, I followed the steps in the tutorial and getting this error:

> > powersync-vue-supabase-todolist@0.0.0 build
> > vue-tsc && vite build
> 
> vite v5.3.4 building for production...
> [plugin:vite:resolve] [plugin vite:resolve] Module "crypto" has been externalized for browser compatibility, imported by "C:/github/vue-supabase-todolist-template-completed/node_modules/bson/lib/bson.mjs". See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
> [plugin:vite:resolve] [plugin vite:resolve] Module "crypto" has been externalized for browser compatibility, imported by "C:/github/vue-supabase-todolist-template-completed/node_modules/bson/lib/bson.mjs". See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details. (x2)
> ✓ 231 modules transformed.
> x Build failed in 12.55s
> error during build:
> [commonjs--resolver] missing field `ctxt`
> file: C:/github/vue-supabase-todolist-template-completed/node_modules/@powersync/web/lib/src/worker/db/open-worker-database.js
>     at Compiler.printSync (C:\github\vue-supabase-todolist-template-completed\node_modules\@swc\core\index.js:194:29)
>     at Object.printSync (C:\github\vue-supabase-todolist-template-completed\node_modules\@swc\core\index.js:348:21)
>     at C:\github\vue-supabase-todolist-template-completed\node_modules\vite-plugin-top-level-await\dist\index.js:103:32
>     at Array.map (<anonymous>)
>     at Object.generateBundle (C:\github\vue-supabase-todolist-template-completed\node_modules\vite-plugin-top-level-await\dist\index.js:95:57)
>     at async Bundle.generate (file:///C:/github/vue-supabase-todolist-template-completed/node_modules/rollup/dist/es/shared/node-entry.js:18122:9)
>     at async file:///C:/github/vue-supabase-todolist-template-completed/node_modules/rollup/dist/es/shared/node-entry.js:20661:27
>     at async catchUnfinishedHookActions (file:///C:/github/vue-supabase-todolist-template-completed/node_modules/rollup/dist/es/shared/node-entry.js:20088:16)
>     at async bundleWorkerEntry (file:///C:/github/vue-supabase-todolist-template-completed/node_modules/vite/dist/node/chunks/dep-D8YhmIY-.js:48142:9)
>     at async workerFileToUrl (file:///C:/github/vue-supabase-todolist-template-completed/node_modules/vite/dist/node/chunks/dep-D8YhmIY-.js:48202:25)

Also, downloaded the completed branch and got the same thing. Please advise.

**Comment by Chriztiaan** [comment]
Hey! This is something that has broken under the `vite-plugin-top-level-await` plugin. They have an issue [here](https://github.com/Menci/vite-plugin-top-level-await/issues/52). We have released an update to our JS SDKs that aims to fix it, but hasn't been applied to the tutorial yet.

Can I ask that you add `"@swc/core": "~1.6.0"` as a dev dependency, nuke your node_modules/lock file and try running your install command again?

**Comment by Chriztiaan** [comment]
https://github.com/powersync-ja/vue-supabase-todolist-template/pull/5
